[processor/transform] Report all parsing errors (#24245)
**Description:**

Follow up from
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23840
to report all errors that occur during parsing. The error isn't pretty,
but this way users know all syntax errors in their OTTL statements up
front.

I played around with trying to format this to make it more readable, but
wasn't able to come up with anything that was satisfactory.

Example config and resulting error:

```yaml
processors:
  transform:
    trace_statements:
      - context: span
        statements: 
        - ParseJSON("...")
        - false
        - set[[]]
    metric_statements:
      - context: datapoint
        statements: 
        - set(attributes, attributes)
        - true
        - set(
```

```
Error: invalid configuration: processors::transform: unable to parse OTTL statement "ParseJSON(\"...\")": editor names must start with a lowercase letter but got 'ParseJSON'; unable to parse OTTL statement "0": statement has invalid syntax: 1:1: unexpected token "0"; unable to parse OTTL statement "set[[]]": statement has invalid syntax: 1:4: unexpected token "[" (expected "(" (Value ("," Value)*)? ")" Key*); unable to parse OTTL statement "1": statement has invalid syntax: 1:1: unexpected token "1"; unable to parse OTTL statement "set(": statement has invalid syntax: 1:5: unexpected token "<EOF>" (expected ")" Key*)
```

I aggregated the errors both in the `Config` struct and on processor
startup, but realistically are highly unlikely to get an error from the
parser on startup because we've already validated the statements. I
updated it just so we're consistent between validating the config and
reporting errors from the OTTL parser.

---------

Co-authored-by: Evan Bradley <evan-bradley@users.noreply.github.com>