Update Prometheus to main (#18507)
I'm trying to implement OTLP receive endpoint in Prometheus
and ran into incompatible types.

Basically this PR: https://github.com/prometheus/prometheus/pull/11935
was merged 3 days after the last release 😭

Error encountered:
```
../../../../pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite@v0.71.0/histograms.go:90:19: cannot use pSpans (variable of type []*prompb.BucketSpan) as type []prompb.BucketSpan in struct literal
../../../../pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite@v0.71.0/histograms.go:92:19: cannot use nSpans (variable of type []*prompb.BucketSpan) as type []prompb.BucketSpan in struct literal
```

But this makes me concerned. If I succeed in getting an OTLP endpoint
merged into Prometheus, it means there is a circular dependency now.

`pkg/translator/prometheusremotewrite` imports `prometheus/prometheus`
and `prometheus/prometheus` will import `pkg/translator/prometheusremotewrite`.

Not sure how to solve the dependency. Will speak to Prometheus team as well.

Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>