[chore] Fix a flaky prometheus test (#38581)
#### Description
Fix flaky TestFromMetricsV2. Previously the test depends on the element
order in a map which is nondeterministic.

#### Link to tracking issue
Fixes
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38556

#### Testing
Before:
```
% go test -run TestFromMetricsV2 -count 10000
--- FAIL: TestFromMetricsV2 (0.00s)
    metrics_to_prw_v2_test.go:46: 
        	Error Trace:	/Users/yang.song/go/src/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite/metrics_to_prw_v2_test.go:46
        	Error:      	Not equal: 
        	            	expected: map[string]*writev2.TimeSeries{"0":(*writev2.TimeSeries)(0x140002046c0), "1":(*writev2.TimeSeries)(0x14000204780)}
        	            	actual  : map[string]*writev2.TimeSeries{"0":(*writev2.TimeSeries)(0x14000176a80), "1":(*writev2.TimeSeries)(0x14000176b38)}        	            	
...
FAIL
exit status 1
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite	0.922s
```

After:
```
% go test -run TestFromMetricsV2 -count 10000
PASS
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite	0.608s
```