[pkg/stanza]: fix operator field config validation (#40728)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description
A few operators with `entry.Field` in their config were validating their
configuration in their `Build` function via a comparison to
`entry.NewNilField`. This was an inaccuracy; when a field is not
provided during the unmarshal step, nothing ever gets run to actually
construct the underlying struct field, meaning that the `entry.Field`
was functionally set to `entry.Field{}`. This is not the same as
`entry.NewNilField` which actually implements and supplies an interface
value under the hood. This caused bad configs to pass validation and led
to collector panic instead of nice failure messages.

This PR changed `entry.NewNilField` to actually produce the correct
pattern for a "nil field", while leaving the original implementation
intact in `entry.NewNoopField` in case it is useful elsewhere (though at
the moment I only saw it used for nil comparisons, which as far as I can
tell were either never useful or something got refactored without being
caught). I also added functionality to
`operatortest.ConfigUnmarshalTest` to check for validation failures by
expecting a particular error when calling the operator's `Build` method.

<!-- Issue number (e.g. #1234) or full URL to issue, if applicable. -->
#### Link to tracking issue
Addresses a panic discovered by #40398.

<!--Describe what testing was performed and which tests were added.-->
#### Testing
Tests were added to each operator's config validation. I tested manually
via a built collector by running the config from the linked issue and
confirming that instead of `panic` I get an error message.
```shell
2025-06-15T01:53:10.582Z        info    service@v0.127.0/service.go:199 Setting up own telemetry...     {"resource": {}}
2025-06-15T01:53:10.582Z        info    builders/builders.go:26 Development component. May change in the future.        {"resource": {}, "otelcol.component.id": "debug", "otelcol.component.kind": "exporter", "otelcol.signal": "logs"}
Error: failed to build pipelines: failed to create "filelog/my-app-name" receiver for data type "logs": remove: field is empty
2025/06/15 01:53:10 collector server run finished with error: failed to build pipelines: failed to create "filelog/my-app-name" receiver for data type "logs": remove: field is empty
```

---------

Co-authored-by: Andrzej Stencel <andrzej.stencel@elastic.co>