[pkg/ottl] Improve OTTL parser error reporting (#23840)
**Description:**

I was playing with an erroneous config like the following and noticed
that the error reporting was confusing:

```yaml
processors:
  filter:
    metrics:
      metric:
        - true
        - false
```

This PR updates the error messages to print the statements next to the
error so it's clear which statement caused the error. To speed up
feedback cycles when changing multiple statements, I've also configured
the parser to attempt to parse each statement so users can see all
errors at once.

Errors now look like this:
```
Error: invalid configuration: processors::filter: unable to parse OTTL statement "drop() where 1": statement has invalid syntax: 1:15: unexpected token "<EOF>" (expected <opcomparison> Value); unable to parse OTTL statement "drop() where 0": statement has invalid syntax: 1:15: unexpected token "<EOF>" (expected <opcomparison> Value)
```

**Testing:** Unit test

Co-authored-by: Evan Bradley <evan-bradley@users.noreply.github.com>