Missing RISC-V binaries (#41560)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

Fixing missing RV64 binaries in all `telemetrygen` builds.


https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/16519577066/job/46718138001

```
 > [linux/riscv64 stage-1 2/2] COPY ./telemetrygen_linux_riscv64 /telemetrygen:
------
Dockerfile:14
--------------------
  12 |     
  13 |     COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
  14 | >>> COPY ./telemetrygen_${TARGETOS}_${TARGETARCH} /telemetrygen
  15 |     
  16 |     ENTRYPOINT ["/telemetrygen"]
--------------------
ERROR: failed to build: failed to solve: failed to compute cache key: failed to calculate checksum of ref ikt1je4gm752tfkb1zrp2v4rl::z7me4ry27x9ebwq1r91c1abm7: "/telemetrygen_linux_riscv64": not found
Reference
  builder-59792c0a-eec9-45ba-add9-60d89801f9b1/builder-59792c0a-eec9-45ba-add9-60d89801f9b10/u3bzkxsj62z7vspt89y8cgwym
Check build summary support
  Build summary supported!
Error: buildx failed with: ERROR: failed to build: failed to solve: failed to compute cache key: failed to calculate checksum of ref ikt1je4gm752tfkb1zrp2v4rl::z7me4ry27x9ebwq1r91c1abm7: "/telemetrygen_linux_riscv64": not found
```

Suppresses #41558

Signed-off-by: Mateusz Urbanek <mateusz.urbanek.98@gmail.com>